# Generated by Django 5.0.6 on 2024-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
