# Generated by Django 5.0.6 on 2024-06-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_es_admin_usuario_es_alumno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='es_alumno',
            field=models.BooleanField(default=True),
        ),
    ]
